import Head from 'next/head'
import Link from 'next/link'
import Cities  from './data.json'


export default function State() {  
  return (
    <div>
      <Head>
        <title>Directory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
          crossorigin="anonymous"
        ></link>
      </Head>

      <main>
        <section class="py-5 text-center container">
          <div className="row py-lg-5">
            <div className="col-lg-6 col-md-8 mx-auto">
              <h1 className="fw-light">Directory</h1>
              <p className="lead text-muted">
                Something short and leading about the collection below—its
                contents, the creator, etc. Make it short and sweet, but not too
                short so folks don’t simply skip over it entirely.
              </p>
            </div>
          </div>
        </section>

       
          <div className="container">
          <div className="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

          {Cities.map(city => {
                        return(
            <div className="col" key={city.id}>
              <div className="card shadow-sm">
                <div className="card-body">                  
                  <h5>{city.state}</h5>
                  <p className="card-text">
                  {city.service}                  
                  </p>
                  <div className="d-flex justify-content-between align-items-center">
                    <div className="btn-group">
                    <Link href={`/directory/${encodeURIComponent(state.stateslug)}`}><button
                        type="button"
                        className="btn btn-sm btn-outline-secondary"
                      >
                        View State
                      </button>
                    </Link>
                    </div>                    
                  </div>
                </div>
              </div>
            </div>
  )}
  )}

          </div>
          </div>
        
      </main>
    </div>
  );
}